SELECT (concat(first_name ,' ', last_name)) as Employees
from employees;

SELECT CONCAT(EMPLOYEES.FIRST_NAME,' ', EMPLOYEES.LAST_NAME) AS EMPLOYEES, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
LEFT JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT DISTINCT JOB_TITLE
FROM EMPLOYEES;

SELECT CONCAT(FIRST_NAME,' ', LAST_NAME) AS EMPLOYEE, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT COUNT(EMPLOYEE_ID) AS TOTAL_EMPLOYEES
FROM EMPLOYEES;

SELECT  DEPARTMENTS.DEPARTMENT_NAME,AVG(EMPLOYEES.SALARY) AS AVG_SALARY
FROM EMPLOYEES
LEFT JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_NAME;

SELECT DEPARTMENTS.DEPARTMENT_NAME, CONCAT(EMPLOYEES.FIRST_NAME, ' ', EMPLOYEES.LAST_NAME) AS EMPLOYEES
FROM DEPARTMENTS
LEFT JOIN EMPLOYEES
ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
ORDER BY DEPARTMENTS.DEPARTMENT_NAME;